analysis_name: 50NiTiSC_0D_1_mono_98_local_maxima # defaults to analysis

## working directory defaults to current working directory
## all relative paths specified herein are assumed to be in the working_dir
## any files not in working_dir should be specified with an absolute path
#working_dir: 

multiprocessing: -1 # "all", or "half", or -1 means all but one, defaults to -1

material:
  definitions: material_niti
  active: NiTi_mono

image_series:
  file:
    stem: /media/DIFFRACTION/CHESS/2015_Dec/50NiTiSC_0D_1/98/ff/ff_%05d.ge2 # can include relative or absolute path
    ids: [845] # or can use globs: ["*2[4-9]"]
  images:
    start: 1
    stop: 3600
    step: 1
  omega:
    start: 0.0
    step: 0.1
    stop: 360.0
  dark: /media/DIFFRACTION/CHESS/2015_Dec/50NiTiSC_0D_1/99/ff/ff_00860.ge2
  flip: h # ~, v, h, hv, vh, cw, ccw

instrument:
  parameters: ge_detector.yml
  detector: # this section is only needed to convert old files to the new spec
    parameters_old: detector_55p618_avg_CHESS_15_dec_APS_cal # the old detector spec, produced by the GUI
    pixels: # this section required to convert from old detector spec
      rows: 2048
      columns: 2048
      size: [0.200, 0.200] # [row height, col width] mm

pre_processing:
  ge_reader_threshold: 50  # Anything less than this will be set to zero on reading GE2 file
  min_blob_size: 125       # Blob containing less than these pixels will be discarded
  min_peak_separation: 5   # Minimum separation between local maxima
  print_spots_info: true   # Print omega, x, y and intensity for the local maxima found
  print_ge: true           # If true, GE2 files will be written to disk (pretty slow for now)
  print_diag_images: false # Print diagnostic PNGs with local maxima overlaid on intensity etc
  radius_gray_dilation_omega: 1  # When writing GE2 files, spot will be dilated by these pixels in omega
  radius_gray_dilation_x: 4      # When writing GE2 files, spot will be dilated by these pixels in x 
  radius_gray_dilation_y: 8      # When writing GE2 files, spot will be dilated by these pixels in y

